name: update readme

on:
  issues:
    types:
      - opened

  workflow_dispatch:

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change README.md
        run: |
          time=$(date +%F -d "${{github.event.issue.updated_at}}")
          echo "- [${{ github.event.issue.title}}](${{github.event.issue.html_url}}) $time" >> README.md
      - name: Commit files  # transfer the new html files back into the repository
        run: |
          git config --local user.name  ${{ github.actor }}
          git add README.md
          git commit -m "(Automated) Update README.md"
      - name: Push changes  # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
  ##################################################
  new-discussion:
    runs-on: ubuntu-latest
    needs: issue-manager
    steps:
      - run: |
          gh api -i graphql -f query='
            mutation {
              createDiscussion(
                input: {repositoryId: "R_kgDOG8AAIw", categoryId: "DIC_kwDOG8AAI84CN7YB",
                  title: "${{github.event.issue.title}}", body: "具体内容请看：${{github.event.issue.html_url}}"
                }
              )
              {
                discussion {
                  id
                  number
                  title
                }
              }
            }
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  issue-reply:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE --body "感谢您提交招聘信息，Rebase 会整理内容，通过公众号发出。"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
